import { ASNData, XMLFormatType } from '../types/asn';

function escapeXml(unsafe: string | number | undefined | null): string {
  if (unsafe === undefined || unsafe === null) return '';
  const str = String(unsafe);
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function formatDateISO(dtStr: string): string {
  if (!dtStr) return '';
  if (dtStr.includes('T')) {
    return dtStr + ':00';
  }
  return dtStr;
}

function formatEDICompactDate(dtStr: string): string {
  if (!dtStr) return '';
  return dtStr.replace(/[-:T]/g, '').slice(0, 12);
}

/**
 * Generates structured XML in standard Despatch Advice format
 */
export function generateStandardXML(data: ASNData): string {
  const { header, items } = data;
  const totalPackages = items.reduce((sum, it) => sum + (it.packageCount || 0), 0);
  const totalItemQty = items.reduce((sum, it) => sum + (it.totalQuantity || 0), 0);

  return `<?xml version="1.0" encoding="UTF-8"?>
<DespatchAdvice xmlns="urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2"
                xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
                xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
                xmlns:edi="urn:edifact:d96a:desadv">
  <!-- Generated by ASN XML & EDIFACT Generator -->
  <InterchangeHeader>
    <SyntaxIdentifier>${escapeXml(header.syntaxIdentifier)}</SyntaxIdentifier>
    <SenderID>${escapeXml(header.unbSender)}</SenderID>
    <RecipientID>${escapeXml(header.unbRecipient)}</RecipientID>
    <InterchangeControlReference>${escapeXml(header.unbInterchangeRef)}</InterchangeControlReference>
    <PreparationDateTime>${escapeXml(formatDateISO(header.documentDate))}</PreparationDateTime>
    <ApplicationReference>DESADV</ApplicationReference>
  </InterchangeHeader>

  <DocumentHeader>
    <DocumentID>${escapeXml(header.asnNumber)}</DocumentID>
    <DocumentTypeCode>${escapeXml(header.documentType)}</DocumentTypeCode>
    <DeliveryNoteNumber>${escapeXml(header.deliveryNoteRef)}</DeliveryNoteNumber>
    <IssueDateTime>${escapeXml(formatDateISO(header.documentDate))}</IssueDateTime>
    <DespatchDateTime>${escapeXml(formatDateISO(header.despatchDate))}</DespatchDateTime>
    <EstimatedDeliveryDateTime>${escapeXml(formatDateISO(header.estimatedDeliveryDate))}</EstimatedDeliveryDateTime>
    <ReferenceDate>${escapeXml(header.referenceDate)}</ReferenceDate>
  </DocumentHeader>

  <TotalShipmentSummary>
    <TotalPackagesCount>${totalPackages}</TotalPackagesCount>
    <TotalItemsQuantity>${totalItemQty}</TotalItemsQuantity>
    <GrossWeight unitCode="KGM">${header.grossWeightKg.toFixed(3)}</GrossWeight>
    <NetWeight unitCode="KGM">${header.netWeightKg.toFixed(3)}</NetWeight>
  </TotalShipmentSummary>

  <Parties>
    <!-- Consignor (Nadawca - CZ) -->
    <ConsignorParty role="CZ">
      <PartyIdentification code="${escapeXml(header.consignor.code)}" qualifier="${escapeXml(header.consignor.codeQualifier || '92')}" />
      <PartyName>${escapeXml(header.consignor.name)}</PartyName>
      <PostalAddress>
        <CityName>${escapeXml(header.consignor.city || '')}</CityName>
        <CountryCode>${escapeXml(header.consignor.countryCode || 'PL')}</CountryCode>
      </PostalAddress>
    </ConsignorParty>

    <!-- Seller (Sprzedawca - SE) -->
    <SellerSupplierParty role="SE">
      <PartyIdentification code="${escapeXml(header.seller.code)}" qualifier="${escapeXml(header.seller.codeQualifier || '92')}" />
      <PartyName>${escapeXml(header.seller.name)}</PartyName>
      <PostalAddress>
        <CityName>${escapeXml(header.seller.city || '')}</CityName>
        <CountryCode>${escapeXml(header.seller.countryCode || 'PL')}</CountryCode>
      </PostalAddress>
    </SellerSupplierParty>

    <!-- Buyer (Kupujący - BY) -->
    <BuyerCustomerParty role="BY">
      <PartyIdentification code="${escapeXml(header.buyer.code)}" qualifier="${escapeXml(header.buyer.codeQualifier || '92')}" />
      <PartyName>${escapeXml(header.buyer.name)}</PartyName>
      <PostalAddress>
        <CityName>${escapeXml(header.buyer.city || '')}</CityName>
        <CountryCode>${escapeXml(header.buyer.countryCode || 'DE')}</CountryCode>
      </PostalAddress>
    </BuyerCustomerParty>

    <!-- Consignee (Odbiorca - CN) -->
    <DeliveryConsigneeParty role="CN">
      <PartyIdentification code="${escapeXml(header.consignee.code)}" qualifier="${escapeXml(header.consignee.codeQualifier || '92')}" />
      <PartyName>${escapeXml(header.consignee.name)}</PartyName>
      <PostalAddress>
        <CityName>${escapeXml(header.consignee.city || '')}</CityName>
        <CountryCode>${escapeXml(header.consignee.countryCode || 'DE')}</CountryCode>
      </PostalAddress>
    </DeliveryConsigneeParty>
  </Parties>

  <ShipmentDeliveryDetails>
    <UnloadingLocation point="${escapeXml(header.unloadingPoint)}" qualifier="${escapeXml(header.unloadingPointQualifier)}" />
    <TransportDetails>
      <TransportStageQualifier>${escapeXml(header.transportStageQualifier)}</TransportStageQualifier>
      <TransportModeCode>${escapeXml(header.transportMode)}</TransportModeCode>
      <CarrierID qualifier="${escapeXml(header.carrierQualifier)}">${escapeXml(header.carrierCode)}</CarrierID>
      ${header.vehiclePlate ? `<VehicleLicensePlate>${escapeXml(header.vehiclePlate)}</VehicleLicensePlate>` : ''}
    </TransportDetails>
  </ShipmentDeliveryDetails>

  <ConsignmentPackagingSequenceList>
${items
  .map(item => {
    const baseNum = parseInt(item.girSerial, 10) || 1;
    const padLen = item.girSerial?.length || 8;
    const packCount = Math.max(1, item.packageCount || 1);
    const girList: string[] = [];

    for (let p = 0; p < packCount; p++) {
      const serialStr = String(baseNum + p).padStart(padLen, '0');
      girList.push(`          <GIRIdentity packageIndex="${p + 1}" typeQualifier="3">
            <SenderCompanyPrefix>${escapeXml(item.girPrefix)}</SenderCompanyPrefix>
            <SerialNumber>${escapeXml(serialStr)}</SerialNumber>
            <FullHandlingUnitID>${escapeXml((item.girPrefix || '') + serialStr)}</FullHandlingUnitID>
            <Qualifier1>UN</Qualifier1>
            <Qualifier2>1J</Qualifier2>
          </GIRIdentity>`);
    }

    return `    <PackingSequence hierarchyLevel="${item.cpsSequence}">
      <PackageDetails>
        <PackageCount>${item.packageCount}</PackageCount>
        <PackageTypeCode qualifier="${escapeXml(item.packageTypeQualifier)}">${escapeXml(item.packageType)}</PackageTypeCode>
        <QuantityPerPackage unitCode="${escapeXml(item.unitOfMeasure)}">${item.qtyPerPackage}</QuantityPerPackage>
        <PackageIdentification>
          <MarkingCode type="${escapeXml(item.pciType)}">${escapeXml(item.pciMarks)}</MarkingCode>
          <!-- Auto-generated GIR Tracking Numbers (${packCount} Handling Units) -->
${girList.join('\n')}
        </PackageIdentification>
      </PackageDetails>

      <DespatchLineItem>
        <ItemIdentification>
          <BuyerPartNumber qualifier="${escapeXml(item.partNumberQualifier)}">${escapeXml(item.partNumber)}</BuyerPartNumber>
          ${item.partDescription ? `<Description>${escapeXml(item.partDescription)}</Description>` : ''}
        </ItemIdentification>
        <DespatchedQuantity unitCode="${escapeXml(item.unitOfMeasure)}">${item.totalQuantity}</DespatchedQuantity>
        <OrderReference>
          <PurchaseOrderNumber>${escapeXml(item.orderNumber)}</PurchaseOrderNumber>
        </OrderReference>
      </DespatchLineItem>
    </PackingSequence>`;
  })
  .join('\n')}
  </ConsignmentPackagingSequenceList>
</DespatchAdvice>`;
}

/**
 * Generates Automotive VDA 4987 / EDIFACT-compliant XML format
 */
export function generateAutomotiveVDAXML(data: ASNData): string {
  const { header, items } = data;

  return `<?xml version="1.0" encoding="UTF-8"?>
<VDA4987_DespatchAdvice messageType="DESADV" version="D96A">
  <MessageHeader>
    <InterchangeSender>${escapeXml(header.unbSender)}</InterchangeSender>
    <InterchangeRecipient>${escapeXml(header.unbRecipient)}</InterchangeRecipient>
    <MessageReferenceNumber>${escapeXml(header.unbInterchangeRef)}</MessageReferenceNumber>
    <CreationDateTime>${escapeXml(formatDateISO(header.documentDate))}</CreationDateTime>
  </MessageHeader>

  <ShipmentHeader>
    <AdviceNumber>${escapeXml(header.asnNumber)}</AdviceNumber>
    <DeliveryNoteNumber>${escapeXml(header.deliveryNoteRef)}</DeliveryNoteNumber>
    <DocumentDate format="203">${escapeXml(formatEDICompactDate(header.documentDate))}</DocumentDate>
    <DespatchDate format="203">${escapeXml(formatEDICompactDate(header.despatchDate))}</DespatchDate>
    <EstimatedArrivalDate format="203">${escapeXml(formatEDICompactDate(header.estimatedDeliveryDate))}</EstimatedArrivalDate>
    <Weights>
      <GrossWeight unit="KGM">${header.grossWeightKg.toFixed(3)}</GrossWeight>
      <NetWeight unit="KGM">${header.netWeightKg.toFixed(3)}</NetWeight>
    </Weights>
    <Routing>
      <UnloadingPoint partnerQualifier="${escapeXml(header.unloadingPointQualifier)}">${escapeXml(header.unloadingPoint)}</UnloadingPoint>
      <CarrierCode partnerQualifier="${escapeXml(header.carrierQualifier)}">${escapeXml(header.carrierCode)}</CarrierCode>
    </Routing>
    <Partners>
      <Supplier code="${escapeXml(header.seller.code)}" role="SE">${escapeXml(header.seller.name)}</Supplier>
      <Consignor code="${escapeXml(header.consignor.code)}" role="CZ">${escapeXml(header.consignor.name)}</Consignor>
      <Customer code="${escapeXml(header.buyer.code)}" role="BY">${escapeXml(header.buyer.name)}</Customer>
      <Consignee code="${escapeXml(header.consignee.code)}" role="CN">${escapeXml(header.consignee.name)}</Consignee>
    </Partners>
  </ShipmentHeader>

  <HandlingUnits>
${items
  .map(
    it => `    <HandlingUnit sequence="${it.cpsSequence}">
      <Packaging>
        <PackageQuantity>${it.packageCount}</PackageQuantity>
        <PackageType>${escapeXml(it.packageType)}</PackageType>
        <PackageCapacity unit="${escapeXml(it.unitOfMeasure)}">${it.qtyPerPackage}</PackageCapacity>
        <LabelData>
          <GIR_Serial prefix="${escapeXml(it.girPrefix)}" serial="${escapeXml(it.girSerial)}" qualifier="1J">${escapeXml(it.girPrefix + it.girSerial)}</GIR_Serial>
          <Marking>${escapeXml(it.pciMarks)}</Marking>
        </LabelData>
      </Packaging>
      <ArticleData>
        <CustomerPartNumber>${escapeXml(it.partNumber)}</CustomerPartNumber>
        <TotalDeliveredQuantity unit="${escapeXml(it.unitOfMeasure)}">${it.totalQuantity}</TotalDeliveredQuantity>
        <PurchaseOrderNumber>${escapeXml(it.orderNumber)}</PurchaseOrderNumber>
      </ArticleData>
    </HandlingUnit>`
  )
  .join('\n')}
  </HandlingUnits>
</VDA4987_DespatchAdvice>`;
}

/**
 * Generates ERP Canonical (SAP / Comarch / Navision) XML format
 */
export function generateERPCanonicalXML(data: ASNData): string {
  const { header, items } = data;

  return `<?xml version="1.0" encoding="UTF-8"?>
<ShipmentNotification>
  <Header>
    <ShipmentNumber>${escapeXml(header.asnNumber)}</ShipmentNumber>
    <DeliveryNote>${escapeXml(header.deliveryNoteRef)}</DeliveryNote>
    <ShipDate>${escapeXml(header.despatchDate.slice(0, 10))}</ShipDate>
    <DeliveryDate>${escapeXml(header.estimatedDeliveryDate.slice(0, 10))}</DeliveryDate>
    <SenderID>${escapeXml(header.consignor.code)}</SenderID>
    <SenderName>${escapeXml(header.consignor.name)}</SenderName>
    <ReceiverID>${escapeXml(header.consignee.code)}</ReceiverID>
    <ReceiverName>${escapeXml(header.consignee.name)}</ReceiverName>
    <UnloadDock>${escapeXml(header.unloadingPoint)}</UnloadDock>
    <TotalGrossWeightKg>${header.grossWeightKg}</TotalGrossWeightKg>
    <TotalNetWeightKg>${header.netWeightKg}</TotalNetWeightKg>
  </Header>
  <Lines>
${items
  .map(
    (it, idx) => `    <Line lineNo="${idx + 1}" cpsSequence="${it.cpsSequence}">
      <ItemCode>${escapeXml(it.partNumber)}</ItemCode>
      <ItemDescription>${escapeXml(it.partDescription || '')}</ItemDescription>
      <Quantity unit="${escapeXml(it.unitOfMeasure)}">${it.totalQuantity}</Quantity>
      <Packages count="${it.packageCount}" type="${escapeXml(it.packageType)}" qtyPerPack="${it.qtyPerPackage}" />
      <GIRLabelNumber>${escapeXml(it.girPrefix + it.girSerial)}</GIRLabelNumber>
      <GIRSerialOnly>${escapeXml(it.girSerial)}</GIRSerialOnly>
      <OrderNumber>${escapeXml(it.orderNumber)}</OrderNumber>
    </Line>`
  )
  .join('\n')}
  </Lines>
</ShipmentNotification>`;
}

export function generateXMLByFormat(data: ASNData, format: XMLFormatType): string {
  switch (format) {
    case 'automotive-vda':
      return generateAutomotiveVDAXML(data);
    case 'erp-canonical':
      return generateERPCanonicalXML(data);
    case 'standard-xml':
    default:
      return generateStandardXML(data);
  }
}
